plugins {
    id 'java'
}

group = 'dev.ultreon.quantum'
version = '0.2.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":logging")

    implementation("com.badlogicgames.gdx:gdx:$gdxVersion")
    implementation("space.earlygrey:shapedrawer:$shapeDrawerVersion")
}

test {
    useJUnitPlatform()
}