image: gradle:8.8-jdk21  # Base Docker image, updated for JDK 21

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  key: "$CI_PROJECT_ID-$CI_COMMIT_REF_SLUG"
  paths:
    - .gradle/wrapper
    - .gradle/caches

build_windows:
  stage: build
  only:
    - dev
    - alpha
    - beta
    - release
    - snapshot
  tags:
    - saas-windows-medium-amd64
  script:
    - echo "Building on Windows with GraalVM 21.0.2 and Java 21..."
    - pwsh -Command "curl -L -o graalvm.zip https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_windows-x64_bin.zip"
    - pwsh -Command "Expand-Archive graalvm.zip -DestinationPath ."
    - cmd.exe /c "set PATH=%CI_PROJECT_DIR%\graalvm-ce-java21-21.0.2\bin;%PATH%"
    - ./gradlew jpackage
  artifacts:
    paths:
      - build/dist/*
    expire_in: 1 week

build_macos:
  stage: build
  only:
    - dev
    - alpha
    - beta
    - release
    - snapshot
  tags:
    - macos
  image: macos-13-xcode-14
  script:
    - echo "Building on macOS with GraalVM 21.0.2 and Java 21..."
    - curl -L -o graalvm.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_macos-aarch64_bin.tar.gz
    - tar -xzf graalvm.tar.gz
    - export PATH="$CI_PROJECT_DIR/graalvm-community-openjdk-21.0.2+13.1/Contents/Home/bin:$PATH"
    - export JAVA_HOME="$CI_PROJECT_DIR/graalvm-community-openjdk-21.0.2+13.1/Contents/Home"
    - ./gradlew jpackage
  artifacts:
    paths:
      - build/dist/*
    expire_in: 1 week

build_linux:
  stage: build
  only:
    - dev
    - alpha
    - beta
    - release
    - snapshot
  tags:
    - saas-linux-small-amd64
  script:
    - echo "Building on Linux with GraalVM 21.0.2 and Java 21..."
    - curl -L -o graalvm.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz
    - tar -xzf graalvm.tar.gz
    - export PATH="$CI_PROJECT_DIR/graalvm-ce-java21-21.0.2/bin:$PATH"
    - ./gradlew jpackage
  artifacts:
    paths:
      - build/dist/*
    expire_in: 1 week
