pluginManagement {
  plugins {
    id("org.jetbrains.gradle.plugin.idea-ext") version "1.3"
  }
}

include 'launcher', 'gameprovider', 'desktop', 'teavm', 'android', 'client', 'server', 'testmod', 'mixinprovider', 'kwantum-api', 'quantum-api'


include 'dedicated'
include 'logging'
include 'block-studio'
include 'agent'
include 'logging'
include 'hydro'
include 'hydro:libgdx-backend'
include 'hydro:libgdx-wgpu-backend'
include 'hydro:lwjgl3-opengl-backend'