plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.0'
}

group = 'dev.ultreon.quantum'
version = rootProject.version

repositories {
    mavenCentral()
}

java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'

    implementation project(":desktop")
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(17)
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    inputs.property "version", version
    filesMatching('xeox.mod.json') {
        expand 'version': version
    }
}
