plugins {
    id 'java'
    id 'java-library'
}

group = 'dev.ultreon.quantum'
version = '0.2.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.slf4j:slf4j-api:$slf4jVersion"
    implementation "com.badlogicgames.gdx:gdx:$gdxVersion"
}

test {
    useJUnitPlatform()
}