plugins {
    id 'java'
    id 'java-library'
}

group = 'dev.ultreon.quantum'
version = '0.2.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation "org.slf4j:slf4j-api:$slf4jVersion"
}

test {
    useJUnitPlatform()
}