plugins {
    id 'java'
    id 'application'
}

group = 'dev.ultreon.quantum'
version = '0.2.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.11.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    def lwjglVersion = "3.3.3"

    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")
    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-opengl"

    implementation 'io.github.spair:imgui-java-binding:1.87.5'
    implementation 'io.github.spair:imgui-java-lwjgl3:1.87.5'
    implementation 'io.github.spair:imgui-java-natives-linux:1.87.5'
    implementation 'io.github.spair:imgui-java-natives-windows:1.87.5'
    implementation 'io.github.spair:imgui-java-natives-macos:1.87.5'

    runtimeOnly "org.lwjgl:lwjgl::natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-glfw::natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-opengl::natives-windows"

    implementation 'net.java.dev.jna:jna:5.15.0'
    implementation 'net.java.dev.jna:jna-platform:5.15.0'
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

compileJava {
    targetCompatibility = sourceCompatibility = 17
}

jar {
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    manifest {
        attributes([
                'Main-Class': 'dev.ultreon.PermissionHelper'
        ])
    }
}

application {
    mainClass = "dev.ultreon.PermissionHelper"
}
