plugins {
    id 'java'
    id 'java-library'
}

group = 'dev.ultreon.quantum'
version = '0.2.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = 'SpongePowered'
        url = 'https://repo.spongepowered.org/repository/maven-public/'
    }
}

dependencies {
    api 'net.fabricmc:sponge-mixin:0.16.1+mixin.0.8.7'

    api project(":logging")

    api "com.google.code.gson:gson:$gsonVersion"
    api "com.google.guava:guava:33.4.8-jre"

    api "org.ow2.asm:asm:9.8"
    api "org.ow2.asm:asm-tree:9.8"
    api "org.ow2.asm:asm-util:9.8"

    implementation "org.slf4j:slf4j-api:$slf4jVersion"


    //noinspection GradleDependency
    implementation platform("org.lwjgl:lwjgl-bom:3.3.3")
    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-opengl"
}

test {
    useJUnitPlatform()
}

java {
    withJavadocJar()
    withSourcesJar()

    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

compileJava {
    targetCompatibility = sourceCompatibility = 17
}

processResources {
    inputs.property "version", version
    filesMatching('xeox.mod.json') {
        expand 'version': version
    }
}

processResources {
    inputs.property "version", version
    filesMatching('xeox.mod.json') {
        expand 'version': version
    }
}