name: Build package.zip
on: [push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21    # Minimum supported
        ]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Build package.zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: chmod +x ./gradlew && ./gradlew packageAll
        env:
          GH_BUILD_NUMBER: ${{ github.run_number }}
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ github.token }}
      - name: Upload build for Mac (M1)
        uses: actions/upload-artifact@v4
        with:
          name: Quantum Voxel Build ${{ github.run_number }}
          path: launcher/build/construo/dist/Quantum Voxel-macM1.zip
      - name: Upload build for Mac (x64)
        uses: actions/upload-artifact@v4
        with:
          name: Quantum Voxel Build ${{ github.run_number }}
          path: launcher/build/construo/dist/Quantum Voxel-macX64.zip
      - name: Upload build for Linux (x64)
        uses: actions/upload-artifact@v4
        with:
          name: Quantum Voxel Build ${{ github.run_number }}
          path: launcher/build/construo/dist/Quantum Voxel-linuxX64.zip
      - name: Upload build for Windows (x64)
        uses: actions/upload-artifact@v4
        with:
          name: Quantum Voxel Build ${{ github.run_number }}
          path: launcher/build/construo/dist/Quantum Voxel-winX64.zip
