# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Create and publish a Docker image
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [21]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Build package.zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build Project using Gradle
        env:
          GH_SHA: ${{ github.sha }}
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ github.token }}
        run: chmod +x ./gradlew && ./gradlew docker-push
