//file:noinspection GroovyUnusedCatchParameter
import java.nio.file.Files
import java.nio.file.Paths

buildscript {
  repositories {
    mavenCentral()

    maven {
      url = "https://oss.sonatype.org/content/repositories/snapshots/"
      name = "sonatype"
    }

    maven {
      url = "https://maven.atlassian.com/3rdparty/"
    }

    gradlePluginPortal()

    google()
  }

  dependencies {
    classpath "com.google.code.gson:gson:2.13.2"
    classpath "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:2.2.20"
    classpath("gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:1.3")
  }
}

plugins {
  id 'org.jetbrains.kotlin.jvm' version '2.2.20'
}

group = "dev.ultreon.quantum"

//*****************//
//     Plugins     //
//*****************//
apply plugin: 'groovy'
apply plugin: 'idea'
apply plugin: 'org.jetbrains.kotlin.jvm'
apply(plugin: "org.jetbrains.gradle.plugin.idea-ext")
apply plugin: 'qvoxel-publisher'

//****************************//
// Setting up main properties //
//****************************//
//projectConfig {
//    type ProjectType.Desktop
//}

evaluationDependsOn(":gameprovider")
evaluationDependsOn(":server")
evaluationDependsOn(":mixinprovider")
evaluationDependsOn(":client")

java {
  withSourcesJar()
  withJavadocJar()

  sourceCompatibility = 11
  targetCompatibility = 17

  toolchain {
    languageVersion = JavaLanguageVersion.of(17)
  }
}

repositories {
  mavenCentral()
  maven {
    url = "https://maven.fabricmc.net"
    name = "FabricMC"
  }
  maven {
    url = "https://jitpack.io"
    name = "JitPack"
  }
  maven {
    url = "https://maven.pkg.github.com/graalvm/graalvm-ce-builds"
    name = "GraalVM"
  }
}

sourceSets {
  lua {
    allSource.srcDirs = []
    resources {
      srcDir 'src/lualib'
    }
  }
}

dependencies {
  implementation api(project(":gameprovider"))
  implementation api(project(":client"))
  implementation api(project(":server"))
  implementation api(project(":dedicated"))
  implementation api(project(":block-studio"))
  runtimeOnly project(":mixinprovider")

  implementation api("com.formdev:flatlaf:3.2.1")

  implementation api("com.badlogicgames.gdx:gdx:$gdxVersion")
  implementation api("com.badlogicgames.gdx:gdx-box2d:$gdxVersion")
  implementation api("com.badlogicgames.ashley:ashley:$ashleyVersion")
  implementation api("com.badlogicgames.gdx:gdx-ai:$aiVersion")
  implementation api("com.badlogicgames.gdx-controllers:gdx-controllers-core:$gdxControllersVersion")
  implementation api("com.badlogicgames.box2dlights:box2dlights:$box2DLightsVersion")

  implementation("org.graalvm.sdk:graal-sdk:24.2.2")

  implementation api("com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion") {
    exclude group: "org.lwjgl", module: "lwjgl"
    exclude group: "org.lwjgl", module: "lwjgl-glfw"
    exclude group: "org.lwjgl", module: "lwjgl-egl"
    exclude group: "org.lwjgl", module: "lwjgl-jemalloc"
    exclude group: "org.lwjgl", module: "lwjgl-openal"
    exclude group: "org.lwjgl", module: "lwjgl-opengl"
    exclude group: "org.lwjgl", module: "lwjgl-opengles"
    exclude group: "org.lwjgl", module: "lwjgl-stb"
  }

  implementation 'org.reflections:reflections:0.10.2'
  implementation api("org.lwjgl:lwjgl:3.3.3!!") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-glfw:3.3.3!!") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-egl:3.3.3!!") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-jemalloc:3.3.3!!") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-openal:3.3.3!!") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-opengl:3.3.3!!") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-opencl:3.3.3!!") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-opengles:3.3.3!!") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-openxr:3.3.3!!") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-stb:3.3.3!!") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl:3.3.3!!:natives-linux") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-glfw:3.3.3!!:natives-linux") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-jemalloc:3.3.3!!:natives-linux") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-openal:3.3.3!!:natives-linux") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-opengl:3.3.3!!:natives-linux") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-openxr:3.3.3!!:natives-linux") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-stb:3.3.3!!:natives-linux") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl:3.3.3!!:natives-macos") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-glfw:3.3.3!!:natives-macos") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-jemalloc:3.3.3!!:natives-macos") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-openal:3.3.3!!:natives-macos") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-opengl:3.3.3!!:natives-macos") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-stb:3.3.3!!:natives-macos") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl:3.3.3!!:natives-windows") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-glfw:3.3.3!!:natives-windows") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-jemalloc:3.3.3!!:natives-windows") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-openal:3.3.3!!:natives-windows") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-opengl:3.3.3!!:natives-windows") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-opengles:3.3.3!!:natives-windows") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-openxr:3.3.3!!:natives-windows") { version { strictly "3.3.3" } }
  implementation api("org.lwjgl:lwjgl-stb:3.3.3!!:natives-windows") { version { strictly "3.3.3" } }
  implementation api("com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop")
  implementation api("com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop")
  implementation api("com.badlogicgames.gdx:gdx-bullet-platform:$gdxVersion:natives-desktop")
  implementation api("com.badlogicgames.gdx-controllers:gdx-controllers-desktop:$gdxControllersVersion")

  // --- Win32 Libraries ---
  implementation api('com.github.Dgzt:gdx-lwjgl3-angle-vulkan:1.0.0') {
    exclude group: "org.lwjgl", module: "lwjgl-opengles"
  }

  // Others
  implementation api("com.github.crykn.guacamole:gdx-desktop:v0.3.5") {
    exclude group: "org.lwjgl", module: "lwjgl"
    exclude group: "org.lwjgl", module: "lwjgl-glfw"
    exclude group: "org.lwjgl", module: "lwjgl-egl"
    exclude group: "org.lwjgl", module: "lwjgl-jemalloc"
    exclude group: "org.lwjgl", module: "lwjgl-openal"
    exclude group: "org.lwjgl", module: "lwjgl-opengl"
    exclude group: "org.lwjgl", module: "lwjgl-opengles"
    exclude group: "org.lwjgl", module: "lwjgl-stb"
  }

  // Discord integration
  compileOnly("com.jagrosh:DiscordIPC:$discordIpcVersion")

  implementation api("ca.weblite:java-objc-bridge:1.2")
  implementation api("com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop")

  // SLF4J
  api "org.slf4j:slf4j-api:$slf4jVersion"


  // Misc
  implementation api("com.raylabz:opensimplex:1.0.3")

  implementation api("space.earlygrey:shapedrawer:$shapeDrawerVersion")

  // ImGui
  implementation api("io.github.spair:imgui-java-binding:$imGuiVersion")
  implementation api("io.github.spair:imgui-java-lwjgl3:$imGuiVersion") {
    exclude group: "org.lwjgl", module: "lwjgl"
    exclude group: "org.lwjgl", module: "lwjgl-bom"
    exclude group: "org.lwjgl", module: "lwjgl-glfw"
    exclude group: "org.lwjgl", module: "lwjgl-egl"
    exclude group: "org.lwjgl", module: "lwjgl-jemalloc"
    exclude group: "org.lwjgl", module: "lwjgl-openal"
    exclude group: "org.lwjgl", module: "lwjgl-opengl"
    exclude group: "org.lwjgl", module: "lwjgl-opengles"
    exclude group: "org.lwjgl", module: "lwjgl-stb"
  }
  implementation api("io.github.spair:imgui-java-natives-linux:$imGuiVersion")
  implementation api("io.github.spair:imgui-java-natives-macos:$imGuiVersion")
  implementation api("io.github.spair:imgui-java-natives-windows:$imGuiVersion")

  implementation api("com.google.code.findbugs:jsr305:$jsrVersion")

  implementation api("org.xbib.elasticsearch:joptsimple:6.3.2.1")
  implementation api("org.apache.logging.log4j:log4j:$log4jVersion")
  implementation api("org.apache.logging.log4j:log4j-core:$log4jVersion")
  implementation api("org.apache.logging.log4j:log4j-api:$log4jVersion")

  // fabric-loader dependencies
  implementation api("org.ow2.asm:asm:${project.asmVersion}")
  implementation api("org.ow2.asm:asm-analysis:${project.asmVersion}")
  implementation api("org.ow2.asm:asm-commons:${project.asmVersion}")
  implementation api("org.ow2.asm:asm-tree:${project.asmVersion}")
  implementation api("org.ow2.asm:asm-util:${project.asmVersion}")

  implementation 'org.mozilla:rhino:1.8.0'
  implementation 'party.iroiro.luajava:luajit:4.0.2'
  runtimeOnly 'party.iroiro.luajava:luajit-platform:4.0.2:natives-desktop'

  implementation 'org.graalvm.sdk:graal-sdk:24.2.2'
  implementation 'org.graalvm.polyglot:polyglot:24.2.2'
  implementation 'org.graalvm.js:js-community:24.2.2'
  implementation("org.graalvm.python:python-community:24.2.2")

  implementation 'net.java.dev.jna:jna:5.17.0'
  implementation 'net.java.dev.jna:jna-platform:5.17.0'
  implementation 'com.github.oshi:oshi-core:6.8.3'

  implementation api("net.fabricmc:sponge-mixin:${project.mixinVersion}") {
    exclude module: 'launchwrapper'
    exclude module: 'guava'
  }

  //noinspection GradleDynamicVersion
  implementation api('net.fabricmc:tiny-mappings-parser:0.3.0+build.17')
  implementation api('net.fabricmc:tiny-remapper:0.8.7')
  //noinspection GradleDynamicVersion
  implementation api('net.fabricmc:dev-launch-injector:0.2.1+build.8')
  implementation api('net.fabricmc:access-widener:2.1.0')

  implementation api("net.fabricmc:fabric-loader:$fabricVersion")

  //noinspection GradleDynamicVersion
  implementation api('net.fabricmc:tiny-mappings-parser:0.3.0+build.17')
  implementation api('net.fabricmc:tiny-remapper:0.8.7')
  //noinspection GradleDynamicVersion
  implementation api('net.fabricmc:dev-launch-injector:0.2.1+build.8')
  implementation api('net.fabricmc:access-widener:2.1.0')

  implementation api("net.fabricmc:fabric-loader:$fabricVersion")
}

compileJava {
  dependsOn ":gameprovider:build"
  dependsOn ":client:build"
}

processResources {
  dependsOn ":gameprovider:build"
  dependsOn ":client:build"
  from(file("$rootProject.projectDir/LICENSE")) { into "META-INF/" }
  exclude "*.pdn", "*.xcf", "*.ps"

  duplicatesStrategy DuplicatesStrategy.INCLUDE
}

jar {
  dependsOn ":gameprovider:build" dependsOn ":client:build"
  //noinspection GroovyAssignabilityCheck
  manifest {
    //noinspection GroovyAssignabilityCheck
    attributes 'Implementation-Title': 'Quantum Voxel',
      'Implementation-Vendor': 'Ultreon Studios',
      project_version: project.mavenVersion,
      'Main-Class': 'dev.ultreon.quantum.DesktopLauncher'
  }

  from zipTree(project(":client").tasks.jar.outputs.files.singleFile), {
    exclude "assets/**/*"
    exclude "icons/**/*"
    exclude "content/**/*"
  }
}

tasks.register('prepareRun', {
  Files.createDirectories(Paths.get(rootProject.projectDir.getAbsolutePath(), "run"))
})

tasks.withType(ProcessResources).configureEach {
  duplicatesStrategy DuplicatesStrategy.INCLUDE
}

tasks.withType(Jar).configureEach {
  duplicatesStrategy DuplicatesStrategy.INCLUDE
}

tasks.register("publishStable", PubTask) {
  channel = "STABLE"
}

tasks.register("publishRc", PubTask) {
  channel = "RC"
}

tasks.register("publishBeta", PubTask) {
  channel = "BETA"
}

tasks.register("publishEdge", PubTask) {
  channel = "EDGE"
}

tasks.register("copyAssets", Copy) {
  from project(":client").tasks.processResources.outputs, {
    include "assets/**/*"
    include "icons/**/*"
    include "content/**/*"
  }

  into rootProject.file("build/assets")
}

tasks.withType(PubTask).configureEach {
  dependsOn "copyAssets", "build"

  clientJar = tasks.jar.outputs.files.singleFile.path
  sourceProject = project
  mainClass = clientMainClass
  assetsPath = rootProject.file("build/assets")
  version = rootProject.version
  fallbackRepo = "https://maven.ultreon.dev/releases"
  outputPath = System.getenv("QVOXEL_PUBLISH_DIR")
  jvmArgs = ["-Xmx8g", "-Xms4g"]

  extraDependencies = [
    "dev.ultreon.quantum:quantum-server:$rootProject.version",
    "dev.ultreon.quantum:quantum-gameprovider:$rootProject.version",
    "dev.ultreon.quantum:dedicated:$rootProject.version",
  ]
}
